[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888

default_environment = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
